services:
  comfyui-nvidia:
    image: mmartial/comfyui-nvidia-docker:latest
    container_name: comfyui-nvidia
    networks:
      - dockge_default
    ports:
      - "8188:8188"  # Accessible externally
    restart: unless-stopped
    volumes:
      - comfyui-run:/comfy/mnt  # Ensure the directory exists
    environment:
      - WANTED_UID=0  # Runs as root
      - WANTED_GID=0
      - SECURITY_LEVEL=normal
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - compute
                - utility

networks:
  dockge_default:
    external: true

volumes:
  comfyui-run:  # This creates a persistent volume for ComfyUI
